### ISSUE TITLE
metaquantome: download tool error

### ISSUE THREAD

**Issue by jraysajulga** [caleb-easterly/metaquantome#28]
Regardless of which databases are checked, running _metaQuantome: download_ gives the following tool error:

```
SelectToolParameterWrapper' object is not iterable
```

**Comment by jraysajulga** [comment]
Seems that the error stems from the $databases variable. It comes as a comma-separated string. It needs to be split prior to being used in the for loop. Adding this line `#set $database_list = str($databases).split(',') ` and replacing $databases with $database_list in the for loop should do the trick.

In summary:

**BEFORE**
```
mkdir -p data &&
        #for $d in $databases
          metaquantome db $d
          --dir data &&
        #end for
        tar --create --file $outfile data
```

**AFTER**
```
mkdir -p data &&
        #set $database_list = str($databases).split(',') 
        #for $d in $database_list
          metaquantome db $d
          --dir data &&
        #end for
        tar --create --file $outfile data
```

**Comment by caleb-easterly** [comment]
resolved - thanks ray!
